export const REGISTER_USER = 'REGISTER USER';
export const ADD_PHONE_NUMBER = 'ADD_PHONE_NUMBER';
export const ADD_BIRTH_DATE = 'ADD_BIRTH_DATE';
export const ADD_ANNIVERSARY_DATE = 'ADD_ANNIVERSARY_DATE';
export const ADD_HOBBIES = 'ADD_HOBBIES';
export const ADD_PROFESSION = 'ADD_PROFESSION';
